### ISSUE TITLE
GHA fails because $CHANGELOG_GITHUB_TOKEN was not found.

### ISSUE THREAD

**Issue by barrientosvctor** [CharMixer/auto-changelog-action#23]
Every time I try to use my workflow returns this error:
```
Warning: No token provided (-t option) and variable $CHANGELOG_GITHUB_TOKEN was not found. This script can make only 50 requests to GitHub API per hour without a token!
	from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	from /usr/local/bundle/gems/github_changelog_generator-1.16.2/lib/github_changelog_generator/octo_fetcher.rb:460:in `check_github_response'
	from /usr/local/bundle/gems/github_changelog_generator-1.16.2/lib/github_changelog_generator/octo_fetcher.rb:102:in `get_all_tags'
	from /usr/local/bundle/gems/github_changelog_generator-1.16.2/lib/github_changelog_generator/generator/generator_tags.rb:10:in `fetch_and_filter_tags'
	from /usr/local/bundle/gems/github_changelog_generator-1.16.2/lib/github_changelog_generator/generator/generator.rb:54:in `block in compound_changelog'
	from /usr/local/bundle/gems/async-1.29.0/lib/async/task.rb:263:in `block in make_fiber'
```

I don't know what is `$CHANGELOG_GITHUB_TOKEN` and I don't know where to insert it.

 This is my yml file:
```yaml
name: Changelog

on:
  pull_request:
    types: [closed]

  release:
    types: [published]

jobs:
  generate_changelog:
    runs-on: ubuntu-22.04
    name: Generate changelog for main branch
    steps:
      - uses: actions/checkout@v1

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.REPO_GITHUB_TOKEN }}

      - name: Commit files
        env:
          CI_USER: ${{ secrets.USERNAME_GITHUB }}
          CI_EMAIL: ${{ secrets.EMAIL_GITHUB }}
        run: |
          git config --local user.email "$CI_EMAIL"
          git config --local user.name "$CI_USER"
          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo "push=true" >> $GITHUB_ENV || echo "No changes to CHANGELOG.md"

      - name: Push changes
        if: env.push == 'true'
        env:
          CI_USER: ${{ secrets.USERNAME_GITHUB }}
          CI_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
        run: |
          git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:main
```
