### ISSUE TITLE
Github action failing due to rate-limiting

### ISSUE THREAD

**Issue by davidjgonzalez** [CharMixer/auto-changelog-action#24]
Just tried to cut a release that includes this plugin, and its failing due to rate limiting by Github. Im not sure why this is happening all of a sudden (ive been using v2.3 for months and its been fine).

Any ideas on why this just started and how to resolve?

```
Fetching tags...

RETRY - Octokit::TooManyRequests: 'GET https://api.github.com/repos/xxx/yyy/tags?per_page=100: 403 - API rate limit exceeded for installation ID 683944. // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'
1 tries in 0.123216574 seconds and 1.0 seconds until the next try

Warning: Can't finish operation: GitHub API rate limit exceeded, changelog may be missing some issues. You can limit the number of issues fetched using the `--max-issues NUM` argument.
#<struct Octokit::RateLimit limit=1000, remaining=0, resets_at=2023-07-14 15:50:29 +0000, resets_in=2234>

RETRY - Octokit::TooManyRequests: 'GET https://api.github.com/repos/xxx/yyy/tags?per_page=100: 403 - API rate limit exceeded for installation ID 683944. // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'
2 tries in 1.322518751 seconds and 1.0 seconds until the next try

Warning: Can't finish operation: GitHub API rate limit exceeded, changelog may be missing some issues. You can limit the number 
of issues fetched using the `--max-issues NUM` argument.

...
```

here is the GA action yaml config for this plugin:

```
     - name: Generate Release Changelog
        id: generate-release-changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          breakingLabel: '### 💥 Breaking'
          enhancementLabel: '### 🚀 Enhancements'
          bugsLabel: '### 🐛 Bug fixes'
          securityLabel: '### 🛡️ Security'
          issuesLabel: '### 📁 Other issues'
          prLabel: '### 📁 Other pull requests'
          addSections: '{"documentation":{"prefix":"### 📖 Documentation","labels":["documentation"]},"tests":{"prefix":"### ✅ Testing","labels":["tests"]}}'
          issues: false
          issuesWoLabels: false
          pullRequests: true
          prWoLabels: true
          author: true
          compareLink: true
          onlyLastTag: true
          stripHeaders: true
          stripGeneratorNotice: true
```
