### ISSUE TITLE
Include commits since a given tag

### ISSUE THREAD

**Issue by mcpierce** [CharMixer/auto-changelog-action#5]
I'm trying to use your action (great work, BTW) but am having an issue with getting it to only include commits since a specific tag.

Using the following configuration:

```
      - name: Generate RELEASE.md
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release_branch: ${{ github.ref }}
          since_tag: v0.5.2-2
```

I'm not getting anything in my RELEASE.md file. I'm using the above to test, which is why I specified the release branch. But if I remove the release branch and since tag then I get nothing at all either.

What could I be doing wrong?

**Comment by charmixer** [comment]
Thanks for trying out the action.

How do you test this? This is only one of the steps from the example - without the checkout / commit / push steps, it will not be updated in your repo.

I haven't heard about any problems with the plain "with token"-example, so that should be working at least.

**Comment by mcpierce** [comment]
@CharMixer What I've been doing is testing on my [fork](https://github.com/mcpierce/comixed) on the project's repo. I delete the testing tag (v0.7.0-0) in the repo, then tag my local changes on the testing branch and then push it and the change then watch the action run. It creates a release and uses the RELEASE.md file created as the body of the release. But each time, as I mentioned, the body is empty.

The full body of my action is:
```
on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout code
        uses: actions/checkout@master
      - name: Generate RELEASE.md
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release_branch: ${{ github.ref }}
          since_tag: v0.5.2-2
      - name: Build project
        run: mvn package -Pci -DskipTests -Dassembly-name=RELEASE
      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: RELEASE.md
          files: |
            comixed-app/target/artifacts/comixed-app-0.7.0-0-RELEASE.zip
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
