### ISSUE TITLE
Cannot able to push changes to Changelog.md to Repo

### ISSUE THREAD

**Issue by ashishpawar517** [CharMixer/auto-changelog-action#8]
see my yaml file.
```yaml
name: Changelog

on: push
    
  # pull_request:
    # types: [closed]

  # release:
    # types: [published]

  # issues:
    # types: [closed, edited]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v1

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1.1
        with:
          token: ${{ secrets.TOKEN }}

      - name: Commit files
        env:
          CI_USER: ${{ secrets.USRNAME }}
          CI_EMAIL: ${{ secrets.EMAIL }}
        run: |
          git config --local user.email "$CI_EMAIL"
          git config --local user.name "$CI_USER"
          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo ::set-env name=push::1 || echo "No changes to CHANGELOG.md"

      - name: Push changes
        if: env.push == 1
        env:
          CI_USER: ${{ secrets.USRNAME }}
          CI_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master

          
```
